### ISSUE TITLE
Does not list my COM ports

### ISSUE THREAD

**Issue by 1soproni** [HackingThings/CAN-Bus-Arduino-Tool#1]
Hi,

I wanted to use you application but it didn't list my available COM ports even I clicked to the reload button.
What could be the problem?
My Arduino is on COM9.
I tried to define it manually but I got an exception.

**Comment by HackingThings** [comment]
What windows version are you running and have you tried running as admin?

- Mickey.

**Comment by 1soproni** [comment]
It's Windows 10 and yes, I tried to run as admin. None of the COM ports are listed.

**Comment by HackingThings** [comment]
What com port number does your arduino get from the os? And what arduino board is it?

- Mickey.

**Comment by 1soproni** [comment]
COM9, arduino uno

**Comment by HackingThings** [comment]
Maybe you still have a sw lovk on that port? Have you tried to do a reset?

- Mickey.

**Comment by 1soproni** [comment]
Yes, I tried to reset already.
I have 4 COM ports listed in the Devicemanager, but none of them in your application :(

**Comment by HackingThings** [comment]
Wierd... You can try and debug it, a breakpoint in the com enum funtion catch will probably show you the reason why it fails

- Mickey.

**Comment by 1soproni** [comment]
Unfortunately I'm not a Visual Studio specialist.

**Comment by HackingThings** [comment]
ok, i rebuilt the debug binaries to show any error messages (CAN_Pipe/bin/Debug/CAN_Pipe.exe) 
Please try to run it again and let me know if it shows any errors

**Comment by 1soproni** [comment]
![screenshot](https://user-images.githubusercontent.com/3668423/28522841-efd98ed4-7079-11e7-8022-88b942c71d19.PNG)
No error but still doesn't work.

**Comment by HackingThings** [comment]
Thanks for your patience, been away for hacker summer camp.
found the problem, the code was listing only COM devices that had "Arduino" in their name, added the option to list all by default.
please download the latest version and let me know if that fixed it.

**Comment by 1soproni** [comment]
Well, I can see com1,7,8 in your software. My arduino is still on com9 :(

**Comment by HackingThings** [comment]
I see, do you have any other arduinos you can plug in and try? This one is a bit tricky, i will need to see if i have one of those laying around to check with.

**Comment by HackingThings** [comment]
Uploading sketch will not work with a clone, if you can upload it manually you should be good with the modification to the dropdown listing all COM devices.
if you still want to have this code work seamlessly for you, please get a genuine UNO R3.
